In [1]:
import pandas as pd
import numpy as np
from pprint import pprint
import sqlite3
from sqlalchemy import create_engine
from pprint import pprint

In [2]:
summary_df = pd.read_csv("summary_df.csv", index_col=0, parse_dates=True)
ranking_df = pd.read_csv("ranking_df.csv", index_col=0, parse_dates=True)
views_df = pd.read_csv("views_df.csv", index_col=0, parse_dates=True)
earnings_df = pd.read_csv("earnings_df.csv", index_col=0, parse_dates=True)

In [3]:
combined_df = pd.merge(summary_df, ranking_df, on='name')
combined_df = pd.merge(combined_df, views_df, on='name')
combined_df = pd.merge(combined_df, earnings_df, on='name')

In [4]:
combined_df.count()

category_x              1315
created                 1626
name                    1626
subscribers             1626
uploads                 1626
views                   1626
category_y              1315
grade                   1626
socialblade_rank        1626
subscriber_rank         1626
view_rank               1626
category_x              1315
subs_last30d_count      1626
views_last30d_count     1626
category_y              1315
max_annual_earnings     1626
max_monthly_earnings    1626
min_annual_earnings     1626
min_monthly_earnings    1626
dtype: int64

In [5]:
cols=pd.Series(combined_df.columns)
for dup in combined_df.columns.get_duplicates(): cols[combined_df.columns.get_loc(dup)]=[dup+'.'+str(d_idx) if d_idx!=0 else dup for d_idx in range(combined_df.columns.get_loc(dup).sum())]
combined_df.columns=cols
combined_df = combined_df[["category_x.1", "created", "name", "subscribers", "uploads", "views", "grade", "socialblade_rank", "subscriber_rank", "view_rank", "subs_last30d_count", "views_last30d_count","min_monthly_earnings", "max_monthly_earnings", "min_annual_earnings", "max_annual_earnings"]]
combined_df = combined_df.dropna().rename(columns={"category_x.1":"category"})
combined_df = combined_df.rename(columns={"min_monthly_earnings":"monthly_earnings"})

C:\Users\uulka\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: 'get_duplicates' is deprecated and will be removed in a future release. You can use idx[idx.duplicated()].unique() instead

In [6]:
combined_df = combined_df[combined_df['subscribers'] >= 0]
combined_df = combined_df[combined_df['views'] > 0]
combined_df = combined_df[combined_df['subs_last30d_count'] > 0]
combined_df = combined_df[combined_df['views_last30d_count'] > 0]
combined_df = combined_df[combined_df['monthly_earnings'] > 0]

In [7]:
combined_df.count()

category                1121
created                 1121
name                    1121
subscribers             1121
uploads                 1121
views                   1121
grade                   1121
socialblade_rank        1121
subscriber_rank         1121
view_rank               1121
subs_last30d_count      1121
views_last30d_count     1121
monthly_earnings        1121
max_monthly_earnings    1121
min_annual_earnings     1121
max_annual_earnings     1121
dtype: int64

In [8]:
combined_df.sort_values('views', ascending=False)

,category,created,name,subscribers,uploads,views,grade,socialblade_rank,subscriber_rank,view_rank,subs_last30d_count,views_last30d_count,monthly_earnings,max_monthly_earnings,min_annual_earnings,max_annual_earnings
9,Music,2014-01-23,netd m√ºzik,12410846,9132,26075394986,A+,18,206,4,278552,614010000,153500,2500000,1800000,29500000
87,Education,2011-06-22,Little Baby Bum - Nursery Rhymes & Kids Songs,17121077,761,18060198768,A,202,107,12,232489,169225500,42300,676900,507700,8100000
17,Music,2011-06-02,El Reino Infantil,17785866,637,17875862536,A+,36,99,13,597507,420153000,10500,1700000,1300000,20200000
3,Education,2006-09-01,Cocomelon - Nursery Rhymes,29627795,386,15233417015,A++,7,28,20,3047454,1264509000,316100,5100000,3800000,60700000
139,People,2011-08-10,BuzzFeedVideo,18001137,5738,14480681233,A,317,94,23,142965,133137300,33300,532500,399400,6400000
62,Music,2010-11-08,GMM GRAMMY OFFICIAL,14351496,6123,14259893905,A,144,154,26,257267,202580100,50600,810300,607700,9700000
156,Games,2012-07-14,DanTDM,20716910,2996,14006688088,A,342,60,27,162638,174923700,43700,699700,524800,8400000
11,Music,2014-03-12,Zee Music Company,28090175,3676,13540612861,A+,23,32,29,1291304,501276000,125300,200000,1500000,24100000
25,Music,2011-01-31,1theK (ÏõêÎçîÏºÄÏù¥),14400628,14082,11605303072,A,57,153,40,469300,308697000,77200,1200000,926100,14800000
1,Howto,2016-11-15,5-Minute Crafts,43993981,2480,10994564885,A++,3,8,43,3212145,708033000,17700,2800000,2100000,3400000
205,Games,2007-02-24,jacksepticeye,20936451,3970,10387870275,A,454,59,54,235009,126749400,31700,50700,380200,6100000
44,Music,2006-08-30,Galinha Pintadinha,14609709,47,10349076814,A,105,147,55,388273,223045200,55800,892200,669100,10700000
219,Comedy,2006-01-08,The Tonight Show Starring Jimmy Fallon,19163718,4876,10286134376,A,490,81,56,274509,149004600,37300,59600,44700,7200000
157,Games,2011-09-15,VanossGaming,23962170,911,10251990263,A,356,41,57,115918,124654800,31200,498600,37400,600000
48,Entertainment,2013-11-03,CookieSwirlC,10316240,2975,10063495577,A,113,309,61,298974,219522900,54900,878100,658600,10500000
160,Music,2006-09-19,Bruno Mars,23320044,67,10045952960,A,359,44,62,224718,122994000,30700,49200,36900,5900000
168,Games,2008-03-02,VEGETTA777,25024815,4909,9781754142,A,379,38,66,370323,114379800,28600,457500,343100,5500000
26,Music,2008-11-24,ŸÇŸÜÿßÿ© ÿ∑ŸäŸàÿ± ÿßŸÑÿ¨ŸÜÿ© | toyoraljanahtv,10418696,2259,9412548905,A,59,305,70,414834,292446000,73100,1200000,877300,1400000
15,Entertainment,2013-01-10,one31,12868270,47493,8863151136,A+,31,193,75,594809,441069000,110300,1800000,1300000,21200000
19,Entertainment,2015-03-28,CKN Toys,10320737,469,8842860491,A+,40,311,76,441422,387192000,96800,1500000,1200000,18600000
66,Entertainment,2005-10-22,LEGO,6811353,19685,8607854711,A,153,622,80,209798,184438500,46100,737800,553300,8900000
90,Music,2012-09-23,Trap Nation,24074600,1541,8379704018,A,199,40,83,469525,169770600,42400,679100,509300,8100000
135,Music,2010-01-03,Coldplay,13413380,208,8348104181,A,305,176,84,208800,134634000,33700,538500,403900,6500000
248,Music,2008-05-09,Wiz Khalifa,16961032,447,8318916044,A,558,110,86,236499,93390900,23300,373600,280200,4500000
18,Music,2009-09-02,Sony Music India,20776398,2332,8277037020,A+,38,62,88,1414457,402774000,100700,1600000,1200000,19300000
98,Music,2006-12-15,Atlantic Records,8827054,1068,8140534905,A,218,395,89,130790,163349700,40800,653400,49000,7800000
254,Entertainment,2007-12-12,DisneyChannelLA,10449600,3622,7949903834,A,568,300,91,178946,96990000,24200,38800,29100,4700000
20,Music,2009-09-02,SonyMusicIndiaVEVO,16548929,3003,7447031962,A+,42,116,101,1017184,378738000,94700,1500000,1100000,18200000
297,Film,2012-07-30,Turma da M√¥nica,9462423,739,7333827918,A,660,354,103,178485,84834000,21200,339300,254500,4100000
85,Games,2012-02-12,rezendeevil,21123414,6906,7301278993,A,197,58,106,585870,173986500,43500,695900,52200,8400000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1474,People,2015-12-24,Niharika Nm,283300,41,35042332,B+,4647,39350,77181,53060,13694730,3400,54800,41100,657300
1304,People,2017-01-22,Milana Tv,162488,119,33886055,B+,4033,67137,79946,89392,18281880,4600,73100,54800,877500
888,Entertainment,2011-01-19,Lewane TV,554316,227,33587877,A-,1972,19641,80831,356379,20912790,5200,83700,62700,100000
485,People,2016-06-28,TinkiPinki,46589,42,31924321,A-,1104,190598,84489,136,28799310,7200,115200,86400,1400000
420,Film,2016-07-14,Ocean Media Entertainment,114906,305,31725405,A,958,90325,85054,3308,86970,22,348,261,4200
1359,Entertainment,2010-08-12,FaberCastellOficial,38794,146,30751044,B+,4325,222130,87618,11179,10795140,2700,43200,32400,518200
1093,Comedy,2015-12-09,Weekend Fail,65311,64,29230240,B+,3483,146146,92114,35766,14637180,3700,58500,43900,702600
1261,News,2017-09-10,My Cricket Knowledge,407906,389,28428278,B+,4106,27243,94617,180991,18506280,4600,7400,55500,888300
1299,Film,2008-09-30,Jaime Ruizi,60353,42,28105658,B+,4184,155787,95737,51558,20826840,5200,83300,62500,999700
1186,Education,2015-08-19,BLA BLA,969140,28,27741514,B+,3735,10345,96997,1599,23436510,5900,93700,70300,1100000
1582,Entertainment,2012-11-23,SnickersIndia,8211,42,27662873,B+,4750,734196,97220,2464,16479720,4100,65900,49400,79100
1468,Nonprofit,2011-11-16,Southeastern Guide Dogs,104038,135,27629472,B+,4530,99624,97519,79597,23100660,5800,92400,69300,1100000
1461,People,2017-12-12,Nihongo Mantappu,413230,92,27199675,B+,4546,26948,98975,225323,13858740,3500,55400,41600,665200
707,People,2015-08-18,Tinto Brass –§–∏–ª—å–º,161695,3,26210229,A-,1568,67293,102883,2529,21945690,5500,87800,65800,1100000
1545,Music,2014-10-01,Seagram's Imperial Blue Superhits Music CDs,11852,26,25462133,B+,4791,558357,107749,3495,9206220,2300,36800,27600,441900
724,Education,2014-10-20,◊©◊ô◊®◊ô◊ù ◊ú◊ô◊ú◊ì◊ô◊ù ◊ï◊§◊¢◊ï◊ò◊ï◊™,74544,45,25087705,A-,1608,131051,106970,66989,21748500,5400,8700,65200,100000
1513,Games,2015-05-15,TalkToHand,231141,159,24417844,B+,4448,48489,110288,99252,11573550,2900,46300,34700,555500
1235,Education,2016-10-15,Safal Ayurved,767730,79,23310975,B+,3733,13539,114816,65996,13533510,3400,54100,40600,649600
654,Film,2017-02-26,Dolly Films,74663,19,22964236,A-,1479,130866,116241,510,22913670,5700,91700,68700,1100000
784,Music,2009-05-12,FatherVEVO,14309,42,22269587,A-,1743,483807,119738,598,20606490,5200,82400,61800,989100
781,Education,2016-11-02,Bamboo Art,210657,906,20563657,A-,1741,52640,129162,3044,464160,116,1900,1400,22300
1358,People,2016-01-16,M√¥t√¥ ƒê·∫πp,33275,850,19978311,B+,4324,24235408,132828,33435,19967910,500,79900,59900,958500
880,Entertainment,2016-05-28,SOUND Effects Public Domain,12896,0,18981151,A-,1956,521059,139502,98,18932880,4700,75700,56800,908800
1279,Autos,2011-07-07,Mercedes-Benz South Africa,13188,98,15206538,B+,4140,515190,172250,114,10904370,2700,43600,32700,523400
1563,Travel,2011-04-28,–ù–µ–∑–∞–≤–∏—Å–∏–º–æ–µ TV.4K,44399,395,15005196,B+,4815,199646,174192,44396,10535790,2600,42100,31600,505700
1591,Games,2017-07-27,Dirty Noob - Minecraft,118506,39,14290495,B+,4708,90397,184673,98272,10202610,2600,40800,30600,489700
1387,People,2016-05-23,Real Health Care In Urdu,249211,326,13095406,B+,4408,44786,198188,2160,10394850,2600,41600,31200,49900
1495,People,2016-06-30,Rahim BK,177970,30,11130076,B+,4693,61658,230590,883,163020,41,652,489,7800
1367,People,2013-04-13,Amazing Studio,151609,2,10638020,B+,4307,71332,240664,152227,10460220,2600,41800,31400,502100
570,Music,2006-09-19,Little Big Town,556978,120,4263840,C+,1707627,19537,550466,3344,13230,3,53,40,635

In [9]:
top5 = combined_df[['category', 'name', 'monthly_earnings', 'subscribers', 'views', 'uploads']]
top5 = top5.groupby('category', as_index=False).apply(lambda x: x.nlargest(5, 'monthly_earnings'))
top5

              category                                           name  \
0  259         Animals                                          Maymo
   368         Animals                               Louie The Beagle
   716         Animals                                       SMG TUBE
   1325        Animals        Hope For Paws - Official Rescue Channel
   1600        Animals                                    cobra123473
1  310           Autos                                          Dekja
   1189          Autos                                   Moto Madness
   1132          Autos                          Toyota Motor Thailand
   1075          Autos                                       AcademeG
   745           Autos                            TOYOTA GAZOO Racing
2  55           Comedy                                      FV FAMILY
   22           Comedy                                   All Of Vines
   106          Comedy                                         Êù±Êµ∑„Ç™„É≥„Ç®„Ç¢
   219          Comedy         The Tonight Show Starring Jimmy Fallon
   136          Comedy                              Jkk Entertainment
3  3         Education                     Cocomelon - Nursery Rhymes
   14        Education                                Toys and Colors
   37        Education                Pinkfong! Kids' Songs & Stories
   78        Education            BabyBus - Kids TV - Songs & Stories
   87        Education  Little Baby Bum - Nursery Rhymes & Kids Songs
4  7     Entertainment                              ‚úø Kids Diana Show
   15    Entertainment                                          one31
   19    Entertainment                                       CKN Toys
   28    Entertainment                                       Shemaroo
   39    Entertainment                             SuperToyzCollector
5  8              Film                                     jorgeembon
   58             Film                                      Goldmines
   56             Film                               OYUNCAKOYNUYORUM
   61             Film                                       Nick Jr.
   84             Film                               HTV2-Vie Channel
...                ...                                            ...
9  130            News                                  The Lallantop
10 318       Nonprofit                                     TEDx Talks
   961       Nonprofit                                        Jubilee
   1468      Nonprofit                        Southeastern Guide Dogs
   1272      Nonprofit                                  TeletonMexico
11 4            People                               Like Nastya Vlog
   21           People                                      BLACKPINK
   47           People                                       mmoshaya
   83           People                               Maria Clara & JP
   86           People                                   David Dobrik
12 73            Shows                               Vijay Television
   153           Shows                                       Sony PAL
   536           Shows                            –ö–£–ö–£–¢–ò–ö–ò - –î–µ—Ç—Å–∫–∏–µ‚Ä¶
   1498          Shows                                     –ú–∞–ª—ã—à–∞—Ä–∏–∫–∏
   409           Shows                                       EBS Kids
13 51           Sports                                 cricket.com.au
   183          Sports                           Toy For Kids [ÌÜ†Ïù¥Ìè¨ÌÇ§Ï¶à]
   206          Sports                                            NFL
   416          Sports                                    FutPar√≥dias
   411          Sports                                 CliveNBAParody
14 272            Tech                                   Google India
   647            Tech                            YASH KE EXPERIMENTS
   547            Tech                                  Unbox Therapy
   642            Tech                               Technical Guruji
   551            Tech                                 Made by Google
15 144          Travel                                   Wheel & Dice
   387          Travel                                 Travel Thirsty
   717          Travel                                        INSIDER
   890          Travel                                     Mark Wiens
   842          Travel                                      Scn sujla

         monthly_earnings  subscribers        views  uploads
0  259              21100      3156432   1385288131      292
   368              20700      1284815    436664461      238
   716               7500       142975     41551016       84
   1325              5800      3535933    799856630      384
   1600               500      2585203   1030112858     2486
1  310              21300      2986447   1352780988     1107
   1189              7800      2829004    626861981     1215
   1132              6100       115172    230564586      820
   1075              5600      3166383    609808356      471
   745               5300        67708     97347171     1160
2  55               49100      1297010    459557383      448
   22               43500      1240056    333380549      246
   106              38900      3939661   3089604390     1169
   219              37300     19163718  10286134376     4876
   136              32400      3990362    756095268       70
3  3               316100     29627795  15233417015      386
   14              117600      7039790   3684704548      177
   37               63500     13356431   6730766097     1091
   78               45600      3093627   2101587050     1114
   87               42300     17121077  18060198768      761
4  7               149800     14542931   4375020758      516
   15              110300     12868270   8863151136    47493
   19               96800     10320737   8842860491      469
   28               76500     12888344   5906383358     6506
   39               70500      5986470   1100917059      163
5  8                64700       438045    571283811      502
   58               55900      7198936   1053351219      362
   56               51800      3504918   1614529859      540
   61               49300      4489507   3725302603     2185
   84               38800      4928652   2637711027     6258
...                   ...          ...          ...      ...
9  130              29900      5059021    879269656     4968
10 318              20400     16011116   2918934719   124580
   961              11300      2117117    271654556      352
   1468              5800       104038     27629472      135
   1272              4500        59821     41248181      929
11 4               170500     13180727   4655061744      193
   21               96600     15871806   3887476837      203
   47               56800      8699273   4745556240      758
   83               46100      6360280   1647119198      405
   86               43300     10133751   3544586273      521
12 73               45900      7466151   4391109706    20028
   153              28500      3989515   1966157500     8245
   536              13700      1589580   1492271479      191
   1498              5200       605644    491333570      323
   409               1600      1864456   2771530164    19611
13 51               39600      1818628    548157878     6877
   183              34300      1119730    290965153       67
   206              26600      4248972   2553251960    15349
   416              17500      5599247   1317375974      215
   411              14200       836508    558058815     3433
14 272              29100      1898612   1651553412      306
   647              17800      1501671    274082404      137
   547              14400     13388083   2524610276     1492
   642              13400     10668354    944720669     2004
   551              12500       568524    125022064      119
15 144              30100       100094     62188730      109
   387              20400      2711007    932649862      398
   717              10900      3459576   1722427430     6441
   890              10500      3290242    607606615      911
   842               6700       435244     80062535      706

[79 rows x 6 columns]

In [10]:
top5.to_csv('top5.csv')

In [11]:
summary = combined_df[['category','name', 'monthly_earnings', 'subscribers', 'views', 'uploads']]
summary = summary.groupby('category').mean().astype(np.int64)
summary = summary.reset_index()

In [12]:
summary.to_csv('summary.csv')

In [13]:
summary.to_dict('records')

[{'category': 'Animals',
  'monthly_earnings': 11120,
  'subscribers': 2141071,
  'views': 738694619,
  'uploads': 696},
 {'category': 'Autos',
  'monthly_earnings': 6455,
  'subscribers': 1358424,
  'views': 383536914,
  'uploads': 661},
 {'category': 'Comedy',
  'monthly_earnings': 13639,
  'subscribers': 5008017,
  'views': 1297376517,
  'uploads': 1199},
 {'category': 'Education',
  'monthly_earnings': 20026,
  'subscribers': 3377660,
  'views': 1589255902,
  'uploads': 488},
 {'category': 'Entertainment',
  'monthly_earnings': 13509,
  'subscribers': 2975862,
  'views': 1279749914,
  'uploads': 4776},
 {'category': 'Film',
  'monthly_earnings': 11943,
  'subscribers': 2200461,
  'views': 1035872918,
  'uploads': 908},
 {'category': 'Games',
  'monthly_earnings': 11325,
  'subscribers': 4437635,
  'views': 1746559285,
  'uploads': 1995},
 {'category': 'Howto',
  'monthly_earnings': 15150,
  'subscribers': 5729361,
  'views': 1225525979,
  'uploads': 731},
 {'category': 'Music',
  'monthly_earnings': 15473,
  'subscribers': 3993768,
  'views': 1983268280,
  'uploads': 1763},
 {'category': 'News',
  'monthly_earnings': 13528,
  'subscribers': 3004897,
  'views': 1169301152,
  'uploads': 40607},
 {'category': 'Nonprofit',
  'monthly_earnings': 10500,
  'subscribers': 4573023,
  'views': 814866732,
  'uploads': 31499},
 {'category': 'People',
  'monthly_earnings': 13248,
  'subscribers': 2643811,
  'views': 916102493,
  'uploads': 2404},
 {'category': 'Shows',
  'monthly_earnings': 18980,
  'subscribers': 3103069,
  'views': 2222480483,
  'uploads': 9679},
 {'category': 'Sports',
  'monthly_earnings': 9761,
  'subscribers': 1391948,
  'views': 579021071,
  'uploads': 2986},
 {'category': 'Tech',
  'monthly_earnings': 9416,
  'subscribers': 2758288,
  'views': 586694548,
  'uploads': 611},
 {'category': 'Travel',
  'monthly_earnings': 11857,
  'subscribers': 2059978,
  'views': 602986353,
  'uploads': 1357}]

In [14]:
conn = sqlite3.connect('YouTube.sqlite')
engine = create_engine("sqlite:///YouTube.sqlite", echo=False)

In [15]:
top5.to_sql('top5', conn, if_exists='replace')
summary.to_sql('summary', conn, if_exists='replace')

In [16]:
pd.read_sql('select category, monthly_earnings, subscribers, views, uploads from summary', conn)

         category  monthly_earnings  subscribers       views  uploads
0         Animals             11120      2141071   738694619      696
1           Autos              6455      1358424   383536914      661
2          Comedy             13639      5008017  1297376517     1199
3       Education             20026      3377660  1589255902      488
4   Entertainment             13509      2975862  1279749914     4776
5            Film             11943      2200461  1035872918      908
6           Games             11325      4437635  1746559285     1995
7           Howto             15150      5729361  1225525979      731
8           Music             15473      3993768  1983268280     1763
9            News             13528      3004897  1169301152    40607
10      Nonprofit             10500      4573023   814866732    31499
11         People             13248      2643811   916102493     2404
12          Shows             18980      3103069  2222480483     9679
13         Sports              9761      1391948   579021071     2986
14           Tech              9416      2758288   586694548      611
15         Travel             11857      2059978   602986353     1357

In [17]:
pd.read_sql('select category, name, monthly_earnings, subscribers, views, uploads from top5', conn)

,category,name,monthly_earnings,subscribers,views,uploads
0,Animals,Maymo,21100,3156432,1385288131,292
1,Animals,Louie The Beagle,20700,1284815,436664461,238
2,Animals,SMG TUBE,7500,142975,41551016,84
3,Animals,Hope For Paws - Official Rescue Channel,5800,3535933,799856630,384
4,Animals,cobra123473,500,2585203,1030112858,2486
5,Autos,Dekja,21300,2986447,1352780988,1107
6,Autos,Moto Madness,7800,2829004,626861981,1215
7,Autos,Toyota Motor Thailand,6100,115172,230564586,820
8,Autos,AcademeG,5600,3166383,609808356,471
9,Autos,TOYOTA GAZOO Racing,5300,67708,97347171,1160
10,Comedy,FV FAMILY,49100,1297010,459557383,448
11,Comedy,All Of Vines,43500,1240056,333380549,246
12,Comedy,Êù±Êµ∑„Ç™„É≥„Ç®„Ç¢,38900,3939661,3089604390,1169
13,Comedy,The Tonight Show Starring Jimmy Fallon,37300,19163718,10286134376,4876
14,Comedy,Jkk Entertainment,32400,3990362,756095268,70
15,Education,Cocomelon - Nursery Rhymes,316100,29627795,15233417015,386
16,Education,Toys and Colors,117600,7039790,3684704548,177
17,Education,Pinkfong! Kids' Songs & Stories,63500,13356431,6730766097,1091
18,Education,BabyBus - Kids TV - Songs & Stories,45600,3093627,2101587050,1114
19,Education,Little Baby Bum - Nursery Rhymes & Kids Songs,42300,17121077,18060198768,761
20,Entertainment,‚úø Kids Diana Show,149800,14542931,4375020758,516
21,Entertainment,one31,110300,12868270,8863151136,47493
22,Entertainment,CKN Toys,96800,10320737,8842860491,469
23,Entertainment,Shemaroo,76500,12888344,5906383358,6506
24,Entertainment,SuperToyzCollector,70500,5986470,1100917059,163
25,Film,jorgeembon,64700,438045,571283811,502
26,Film,Goldmines,55900,7198936,1053351219,362
27,Film,OYUNCAKOYNUYORUM,51800,3504918,1614529859,540
28,Film,Nick Jr.,49300,4489507,3725302603,2185
29,Film,HTV2-Vie Channel,38800,4928652,2637711027,6258
...,...,...,...,...,...,...
49,News,The Lallantop,29900,5059021,879269656,4968
50,Nonprofit,TEDx Talks,20400,16011116,2918934719,124580
51,Nonprofit,Jubilee,11300,2117117,271654556,352
52,Nonprofit,Southeastern Guide Dogs,5800,104038,27629472,135
53,Nonprofit,TeletonMexico,4500,59821,41248181,929
54,People,Like Nastya Vlog,170500,13180727,4655061744,193
55,People,BLACKPINK,96600,15871806,3887476837,203
56,People,mmoshaya,56800,8699273,4745556240,758
57,People,Maria Clara & JP,46100,6360280,1647119198,405
58,People,David Dobrik,43300,10133751,3544586273,521
59,Shows,Vijay Television,45900,7466151,4391109706,20028
60,Shows,Sony PAL,28500,3989515,1966157500,8245
61,Shows,–ö–£–ö–£–¢–ò–ö–ò - –î–µ—Ç—Å–∫–∏–µ‚Ä¶,13700,1589580,1492271479,191
62,Shows,–ú–∞–ª—ã—à–∞—Ä–∏–∫–∏,5200,605644,491333570,323
63,Shows,EBS Kids,1600,1864456,2771530164,19611
64,Sports,cricket.com.au,39600,1818628,548157878,6877
65,Sports,Toy For Kids [ÌÜ†Ïù¥Ìè¨ÌÇ§Ï¶à],34300,1119730,290965153,67
66,Sports,NFL,26600,4248972,2553251960,15349
67,Sports,FutPar√≥dias,17500,5599247,1317375974,215
68,Sports,CliveNBAParody,14200,836508,558058815,3433
69,Tech,Google India,29100,1898612,1651553412,306
70,Tech,YASH KE EXPERIMENTS,17800,1501671,274082404,137
71,Tech,Unbox Therapy,14400,13388083,2524610276,1492
72,Tech,Technical Guruji,13400,10668354,944720669,2004
73,Tech,Made by Google,12500,568524,125022064,119
74,Travel,Wheel & Dice,30100,100094,62188730,109
75,Travel,Travel Thirsty,20400,2711007,932649862,398
76,Travel,INSIDER,10900,3459576,1722427430,6441
77,Travel,Mark Wiens,10500,3290242,607606615,911
78,Travel,Scn sujla,6700,435244,80062535,706